# Importing Everything Needed

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error, r2_score , mean_absolute_error
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from tensorflow.keras import layers, models, callbacks
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold

pd.pandas.set_option('display.max_columns',None)

In [ ]:
df = pd.read_csv("train.csv")

In [ ]:
df_test = pd.read_csv("test.csv")

In [ ]:
df.sample(9)

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
20011,Dealer,0,1,2,BHK,1272.671380,1,1,"Raj Nagar Extension,Ghaziabad",26.900926,75.775927,41.4
21283,Dealer,0,0,3,BHK,1350.210970,1,1,"Gorewada,Lalitpur",24.690280,78.418890,48.0
21745,Owner,0,0,3,BHK,2271.512560,1,1,"Sector-28 Rohtak,Rohtak",28.870999,76.636211,85.0
27327,Owner,0,0,2,BHK,868.055556,1,1,"Baguihati,Kolkata",22.617564,88.427982,20.0
20819,Owner,0,1,3,BHK,1238.174736,1,1,"Sector 63,Faridabad",28.621800,77.383100,44.5
5716,Dealer,0,1,2,BHK,1150.054765,1,1,"Ahinsa Khand 2,Ghaziabad",28.919600,76.897200,42.0
25445,Dealer,1,1,3,BHK,875.426771,0,0,"Baner,Pune",18.558319,73.775880,100.0
12662,Dealer,0,1,1,BHK,747.126437,1,1,"Sector - 1 Dharuhera,Dharuhera",28.211607,76.787033,15.6
29244,Dealer,1,0,2,BHK,1209.612817,0,1,"Althan,Surat",21.151992,72.810020,45.3

In [ ]:
df_test.sample(9)

,UNDER_CONSTRUCTION,RERA,BHK_NO.,SQUARE_FT,READY_TO_MOVE,RESALE,LONGITUDE,LATITUDE,Bangalore,Chennai,Ghaziabad,Jaipur,Kolkata,Lalitpur,Maharashtra,Mumbai,Noida,Other,Pune,Builder,Dealer,Owner
37140,0,0,2,1070.205479,1,1,10.986809,76.997595,0,0,0,0,0,0,0,0,0,1,0,0,0,1
3399,0,0,1,550.000000,1,1,18.700817,73.685514,0,0,0,0,0,0,0,0,0,0,1,0,0,1
6291,0,0,2,990.998431,1,1,24.690280,78.418890,0,0,0,0,0,1,0,0,0,0,0,0,1,0
57940,1,1,2,1245.056394,0,1,19.058710,72.899690,0,0,0,0,0,0,1,0,0,0,0,0,1,0
67894,0,0,2,900.090009,1,1,12.808137,77.583080,1,0,0,0,0,0,0,0,0,0,0,0,0,1
45638,0,1,3,2471.013115,1,1,30.661104,76.746082,0,0,0,0,0,0,0,0,0,1,0,0,1,0
54094,0,0,2,1270.168211,1,1,39.912312,-86.212488,0,0,0,0,0,0,0,0,0,1,0,0,0,1
42080,0,0,2,1080.139373,1,1,22.541110,88.337780,0,0,0,0,1,0,0,0,0,0,0,0,1,0
27731,0,0,2,900.090009,1,1,21.167998,79.112474,0,0,0,0,0,0,0,0,0,1,0,0,0,1

In [ ]:
df.shape

(29451, 12)

In [ ]:
df.info()
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  object
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  object
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  object
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 2.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68720 entries, 0 to 68719
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   POSTED_BY           68720 non-null  object
 1   UNDER_CONSTRUCTION  68720 non-null  int64
 2   RERA                68720 non-null  int64
 3   BHK_NO.             68720 non-null  int64
 4   BHK_OR_RK           68720 non-null  object
 5   SQUARE_FT           68720 non-null  float64
 6   READY_TO_MOVE       68720 non-null  int64
 7   RESALE              68720 non-null  int64
 8   ADDRESS             68720 non-null  object
 9   LONGITUDE           68720 non-null  float64
 10  LATITUDE            68720 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 5.8+ MB

# Year_Built is ready to use no feature Engineering

In [ ]:
for col in df.columns:
    print(f"\nColumn: {col}")
    print(df[col].value_counts(dropna=False).head())

Column: POSTED_BY
POSTED_BY
Dealer     18291
Owner      10538
Builder      622
Name: count, dtype: int64

Column: UNDER_CONSTRUCTION
UNDER_CONSTRUCTION
0    24157
1     5294
Name: count, dtype: int64

Column: RERA
RERA
0    20088
1     9363
Name: count, dtype: int64

Column: BHK_NO.
BHK_NO.
2    13324
3    10546
1     3574
4     1723
5      190
Name: count, dtype: int64

Column: BHK_OR_RK
BHK_OR_RK
BHK    29427
RK        24
Name: count, dtype: int64

Column: SQUARE_FT
SQUARE_FT
1000.0    479
1250.0    294
800.0     202
1200.0    179
1600.0    125
Name: count, dtype: int64

Column: READY_TO_MOVE
READY_TO_MOVE
1    24157
0     5294
Name: count, dtype: int64

Column: RESALE
RESALE
1    27377
0     2074
Name: count, dtype: int64

Column: ADDRESS
ADDRESS
Zirakpur,Chandigarh              509
Whitefield,Bangalore             230
Raj Nagar Extension,Ghaziabad    215
Sector-137 Noida,Noida           139
New Town,Kolkata                 131
Name: count, dtype: int64

Column: LONGITUDE
LONGITUDE
24.690280    1009
12.969910     671
30.662283     509
22.541110     479
19.058710     242
Name: count, dtype: int64

Column: LATITUDE
LATITUDE
78.418890    1009
77.597960     671
76.822397     509
88.337780     479
72.899690     242
Name: count, dtype: int64

Column: TARGET(PRICE_IN_LACS)
TARGET(PRICE_IN_LACS)
110.0    795
100.0    770
120.0    652
130.0    598
45.0     583
Name: count, dtype: int64

## ADDRESS COLUMN

In [ ]:
df['City'] = df['ADDRESS'].apply(lambda x: x.split(',')[-1].strip())
df_test['City'] = df_test['ADDRESS'].apply(lambda x: x.split(',')[-1].strip())

In [ ]:
# Top 10 most frequent cities
print(df['City'].value_counts().head(10))

City
Bangalore      4340
Lalitpur       2993
Mumbai         2023
Pune           1991
Noida          1767
Kolkata        1709
Maharashtra    1579
Chennai        1255
Ghaziabad      1087
Jaipur          962
Name: count, dtype: int64

In [ ]:
# 1. Extract top cities from train only (threshold = 900)
top_cities = df['City'].value_counts()[df['City'].value_counts() >= 900].index

# 2. Train set processing
df['City_mod'] = df['City'].where(df['City'].isin(top_cities), 'Other')
df_city_dummies = pd.get_dummies(df['City_mod'], drop_first=False).astype(int)
df = pd.concat([df.drop(columns=['City']), df_city_dummies], axis=1)

# 3. Test set processing (use SAME top_cities)
df_test['City_mod'] = df_test['City'].where(df_test['City'].isin(top_cities), 'Other')
df_test_city_dummies = pd.get_dummies(df_test['City_mod'], drop_first=False).astype(int)

# 4. Align test dummies with train dummies (to ensure same columns)
df_test_city_dummies = df_test_city_dummies.reindex(columns=df_city_dummies.columns, fill_value=0)
df_test = pd.concat([df_test.drop(columns=['City']), df_test_city_dummies], axis=1)

print("Train shape:", df.shape)
print("Test shape:", df_test.shape)

Train shape: (29451, 24)
Test shape: (68720, 23)

## One Hot Encoding

In [ ]:
# Train
dummies_train = pd.get_dummies(df['POSTED_BY'], drop_first=False).astype(int)
dummies_train = dummies_train.reindex(columns=['Builder', 'Dealer', 'Owner'], fill_value=0)
df = pd.concat([df.drop(columns=['POSTED_BY']), dummies_train], axis=1)

# Test
dummies_test = pd.get_dummies(df_test['POSTED_BY'], drop_first=False).astype(int)
dummies_test = dummies_test.reindex(columns=['Builder', 'Dealer', 'Owner'], fill_value=0)
df_test = pd.concat([df_test.drop(columns=['POSTED_BY']), dummies_test], axis=1)

In [ ]:
df_test = df_test.drop(columns=['BHK_OR_RK'])
df = df.drop(columns=['BHK_OR_RK'])

In [ ]:
df['BHK_NO.'] = df['BHK_NO.'].astype(int)
df_test['BHK_NO.'] = df_test['BHK_NO.'].astype(int)

In [ ]:
df.drop(columns=['ADDRESS'],inplace=True)
df_test.drop(columns=['ADDRESS'],inplace=True)
df.drop(columns=['City_mod'],inplace=True)
df_test.drop(columns=['City_mod'],inplace=True)

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=['TARGET(PRICE_IN_LACS)']),df['TARGET(PRICE_IN_LACS)'],test_size=0.2,random_state=42)

In [ ]:
SS=StandardScaler()
X_train=SS.fit_transform(X_train)
X_test=SS.transform(X_test)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score

# Initialize model
gbr = GradientBoostingRegressor(
    n_estimators=200,   # number of boosting stages
    learning_rate=0.1,  # step size shrinkage
    max_depth=3,        # depth of individual trees
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

# Train
gbr.fit(X_train, Y_train)

# Predict
y_pred_gbr = gbr.predict(X_test)

# Evaluate
print("Gradient Boosting R² Score:", r2_score(Y_test, y_pred_gbr))

Gradient Boosting R² Score: 0.785656923623588

In [ ]:
import joblib
joblib.dump(gbr, 'gradient_boosting_model.pkl')

# Load the model later
loaded_model = joblib.load('gradient_boosting_model.pkl')

# Test prediction
y_pred = loaded_model.predict(df_test)
print(y_pred[:5])

[24562.16652007 24501.21689133 25418.28745018 25400.49290071
 24562.16652007]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but GradientBoostingRegressor was fitted without feature names
  warnings.warn(

In [ ]:
import pandas as pd

# Column names exactly as per your dataset
columns = [
    'UNDER_CONSTRUCTION','RERA','BHK_NO.','SQUARE_FT','READY_TO_MOVE','RESALE',
    'LONGITUDE','LATITUDE',
    'Bangalore','Chennai','Ghaziabad','Jaipur','Kolkata','Lalitpur','Maharashtra','Mumbai','Noida','Other','Pune',
    'Builder','Dealer','Owner'
]

# Sample inputs
sample_inputs = pd.DataFrame([
    # Bangalore, 3 BHK, Builder
    [0,1,3,1450,1,1,12.9716,77.5946,1,0,0,0,0,0,0,0,0,0,0,1,0,0],

    # Chennai, 2 BHK, Dealer
    [0,1,2,1200,1,1,13.0827,80.2707,0,1,0,0,0,0,0,0,0,0,0,0,1,0],

    # Noida, 3 BHK, Owner
    [0,1,3,1600,1,1,28.5355,77.3910,0,0,0,0,0,0,0,0,0,0,0,0,0,1],

    # Kolkata, 2 BHK, Builder
    [0,1,2,1100,1,1,22.5726,88.3639,0,0,0,0,1,0,0,0,0,0,0,1,0,0],

    # Pune, 1 BHK, Dealer
    [0,1,1,650,1,1,18.5204,73.8567,0,0,0,0,0,0,0,0,0,0,0,0,1,0]
], columns=columns)

# Scale the entire DataFrame using your previously fitted scaler
sample_inputs_scaled = SS.transform(sample_inputs)

# Predict
predicted_prices = loaded_model.predict(sample_inputs_scaled)

# Print predictions
for i, price in enumerate(predicted_prices):
    print(f"Sample {i+1} Predicted Price (in Lacs): {price}")

Sample 1 Predicted Price (in Lacs): 82.11502174056204
Sample 2 Predicted Price (in Lacs): 71.2674325541953
Sample 3 Predicted Price (in Lacs): 83.72507446362475
Sample 4 Predicted Price (in Lacs): 44.48964140102686
Sample 5 Predicted Price (in Lacs): 37.609341751008635

In [ ]:
import joblib

# Save model
joblib.dump(loaded_model, "house_price_model.pkl")

['house_price_model.pkl']

In [ ]:
# from sklearn.preprocessing import PowerTransformer

# pt = PowerTransformer(method='yeo-johnson')
# Y_train_yj = pt.fit_transform(Y_train.values.reshape(-1,1))

In [ ]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Dropout , BatchNormalization
# from tensorflow.keras.callbacks import EarlyStopping
# from tensorflow.keras.optimizers import Adam

# # Build model
# model = Sequential([
#     Dense(128, activation='relu', input_dim=X_train.shape[1]),
#     Dropout(0.2),
#     BatchNormalization(),
#     Dense(64, activation='relu'),
#     Dropout(0.2),
#     BatchNormalization(),
#     Dense(32, activation='relu'),
#     Dense(1)   # Output layer
# ])

# # Compile with tuned learning rate
# model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_absolute_error')

# # Early stopping
# early_stop = EarlyStopping(monitor='val_loss', patience=7, restore_best_weights=True)

# # Train
# history = model.fit(
#     X_train, Y_train,
#     validation_split=0.2,
#     epochs=100,
#     batch_size=32,
#     callbacks=[early_stop],
#     verbose=1
# )

# # Evaluate
# y_pred = model.predict(X_test)
# score = r2_score(Y_test, y_pred)
# print("R² Score:", score)

In [ ]:
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import r2_score

# # Initialize model
# rf = RandomForestRegressor(
#     n_estimators=200,   # number of trees
#     max_depth=None,     # let trees grow fully
#     min_samples_split=2,
#     min_samples_leaf=1,
#     random_state=42,
#     n_jobs=-1           # use all CPU cores
# )

# # Train
# rf.fit(X_train, Y_train)

# # Predict
# y_pred_rf = rf.predict(X_test)

# # Evaluate
# print("Random Forest R² Score:", r2_score(Y_test, y_pred_rf))

In [ ]:
# from lightgbm import LGBMRegressor
# from sklearn.metrics import r2_score

# # Initialize model
# lgbm = LGBMRegressor(
#     n_estimators=200,      # number of boosting rounds
#     learning_rate=0.1,     # step size shrinkage
#     max_depth=-1,          # -1 means no limit
#     num_leaves=31,         # controls complexity (higher = more complex)
#     min_child_samples=20,  # minimum data in one leaf
#     subsample=1.0,         # row sampling
#     colsample_bytree=1.0,  # feature sampling
#     random_state=42,
#     n_jobs=-1
# )

# # Train
# lgbm.fit(X_train, Y_train)

# # Predict
# y_pred_lgbm = lgbm.predict(X_test)

# # Evaluate
# print("LightGBM R² Score:", r2_score(Y_test, y_pred_lgbm))

In [ ]:
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.model_selection import RandomizedSearchCV
# from sklearn.metrics import r2_score
# import pandas as pd
# import numpy as np

# # Random Forest hyperparameter space
# param_dist_rf = {
#     "n_estimators": [100, 300, 500, 800, 1200],
#     "max_depth": [None, 5, 10, 20, 30],
#     "min_samples_split": [2, 5, 10],
#     "min_samples_leaf": [1, 2, 4],
#     "max_features": ["auto", "sqrt", "log2"],
#     "bootstrap": [True, False]
# }

# # Base RF model
# rf_cv = RandomForestRegressor(
#     random_state=42,
#     n_jobs=-1
# )

# # Randomized Search CV
# rf_rand = RandomizedSearchCV(
#     estimator=rf_cv,
#     param_distributions=param_dist_rf,
#     n_iter=25,
#     scoring="r2",
#     cv=3,
#     verbose=2,
#     random_state=42,
#     n_jobs=-1,
#     return_train_score=True
# )

# # Fit the model
# rf_rand.fit(X_train, Y_train)

# # Store results
# results_rf = pd.DataFrame(rf_rand.cv_results_)
# cols = ["params", "mean_test_score", "std_test_score", "mean_train_score"]
# results_rf = results_rf[cols].sort_values(by="mean_test_score", ascending=False)
# print(results_rf)

# # Best model evaluation
# best_rf_model = rf_rand.best_estimator_
# y_pred_rf = best_rf_model.predict(X_test)
# print("Best Params:", rf_rand.best_params_)
# print("CV Tuned RF R2:", r2_score(Y_test, y_pred_rf))

In [ ]:
# import matplotlib.pyplot as plt

# plt.plot(history.history['loss'])
# plt.plot(history.history['val_loss'])

In [ ]:
# # Save model in Keras format
# model.save("house_price_model.h5")

# # Download
# from google.colab import files
# files.download("house_price_model.h5")

In [ ]:
# from google.colab import files
# files.download("preprocessor.pkl")

In [ ]:
# import pandas as pd

# # Example input row after preprocessing
# example_input = pd.DataFrame([{
#     "State": 15,
#     "Locality": 84,
#     "Property_Type": 0.0,       # Apartment
#     "BHK": 2,
#     "Size_in_SqFt": 1500,
#     "Price_per_SqFt": 0.12,
#     "Year_Built": 2010,
#     "Furnished_Status": 2.0,    # Furnished
#     "Floor_No": 5,
#     "Total_Floors": 10,
#     "Age_of_Property": 12,
#     "Nearby_Schools": 8,
#     "Nearby_Hospitals": 3,
#     "Public_Transport_Accessibility": 2.0,  # High
#     "Parking_Space": 1.0,       # Yes
#     "Security": 1.0,            # Yes
#     "Facing": 3,                # West
#     "Owner_Type": 2,            # Owner
#     "City_encoded": 0.135,
#     "Is_Ready_to_Move": 1,
#     "Clubhouse": 1,
#     "Garden": 1,
#     "Gym": 0,
#     "Playground": 1,
#     "Pool": 1
# }])

# print(example_input.shape)
# print(example_input.head())